#!/bin/bash
r="\e[91m"
w="\e[0m"
clear
printf """$r
	       .MMM...MMMMMMM
              MMMMMMMMMMMMMMMMMM
             MMMMMMMMMMMMMMMMMMMM.
            MMMMMMMMMMMMMMMMMMMMMM
           ,MMMMMMMMMMMMMMMMMMMMMMM
            MMMMMMMMMMMMMMMMMMMMMMMM
      .MMMM   MMMMMMMMMMMMMMMMMMMMMM
     MMMMMM     MMMMMMMMMMMMMMMMMMMM.
    MMMMMMMM      MMMMMMMMMMMMMMMMMM .
    MMMMMMMMM.        MMMMMMMMMMMMM  MM.
    MMMMMMMMMMM.                     MMMM
     MMMMMMMMMMMMM.                 ,MMMMM.
      MMMMMMMMMMMMMMMMM.          ,MMMMMMMM.
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
          MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
             MMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
                 MMMMMMMMMMMMMMMMMMMMMMMM
                      MMMMMMMMMMMMMMMMM \n$w"""
printf "Tool Name : Termux Theme\n"
printf "YouTube	  : @devstackid\n"
printf "_____________________ $r.RedHat.$w _______________________\n"
echo ''
